## Linear Algebra Assignment

Answer the following questions by completing the corresponding scripts. Make sure you don't see any more packages than the ones provided here.



In [77]:
import numpy as np

### Question 1. [2 pts]

Let a square matrix $M$ have the block form shown below, where $A$, $B$ and $C$ are $n\times n$ invertible matrices.
$$
M = \begin{bmatrix}A & B \\ C & 0
\end{bmatrix}
$$
Provide an expression for each block in the inverse
$$
M^{-1} = \begin{bmatrix}P_{11} & P_{12} \\ P_{21} & P_{22}
\end{bmatrix}
$$
in terms of $A$, $B$, $C$, $A^{-1}$, $B^{-1}$ and $C^{-1}$.

Implement these expressions in the functions below. Pay close attention to how the cells below compute the inverses for the blocks for you. You should not compute any additional inverses in your solution.

In [78]:
def P11_fnc(A,B,C,Ai,Bi,Ci):

    return np.zeros(A.shape)

def P12_fnc(A,B,C,Ai,Bi,Ci):

    return Ci

def P21_fnc(A,B,C,Ai,Bi,Ci):

    return Bi

def P22_fnc(A,B,C,Ai,Bi,Ci):

    return -np.dot(Bi, np.dot(A, Ci))


Running first of tests. [1 pt]

In [79]:
def invM_fnc(A,B,C):
    Ai = np.linalg.inv(A)
    Bi = np.linalg.inv(B)
    Ci = np.linalg.inv(C)

    P11 = P11_fnc(A,B,C,Ai,Bi,Ci)
    P12 = P12_fnc(A,B,C,Ai,Bi,Ci)
    P21 = P21_fnc(A,B,C,Ai,Bi,Ci)
    P22 = P22_fnc(A,B,C,Ai,Bi,Ci)

    return np.block([[P11,P12],[P21,P22]])

# Calculating the inverse of an example using the functions
A = np.array([[1,2],[3,4]])
B = np.array([[2,3],[0,1]])
C = np.array([[4,0],[5,7]])
invM = invM_fnc(A,B,C)
print('Inverse of M Computed:')
print(invM)

# This is the actual inverse
invM_true = np.array([[0,0,0.2500,0],[0,0,-0.1786,0.1429],
  [0.5000,-1.5000,0.1071,0.7143],[0,1.0000,-0.0357,-0.5714]])

# This is the function that we will be using to check accuracy
def AlmostEqual(P, Q, digits):
    epsilon = 10 ** -digits
    return np.linalg.norm(P-Q) < epsilon

# Checking that the dimensions are correct
assert not ((invM.shape != 2*np.array(A.shape)).any())

# Checking that the values are close enough
assert AlmostEqual(invM_true,invM,3)

Inverse of M Computed:
[[ 0.          0.          0.25        0.        ]
 [ 0.          0.         -0.17857143  0.14285714]
 [ 0.5        -1.5         0.10714286  0.71428571]
 [ 0.          1.         -0.03571429 -0.57142857]]


Running second set of tests. [1 pt]

In [80]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


### Question 2. [2 pts]

Let a square matrix $M$ have the form shown below, where $a$ and $b$ are non-zero scalars.
$$
M = \begin{bmatrix}a & b-a \\ 0 & b
\end{bmatrix}
$$

For an integer $n>0$, provide an expression for each entry in
$$
M^{n} = \begin{bmatrix}Q_{11} & Q_{12} \\ Q_{21} & Q_{22}
\end{bmatrix}
$$
in terms of $a$, $b$ and $n$.

Implement these expressions in the functions below.

In [81]:
def Q11_fnc(a,b,n):

    return a**n

def Q12_fnc(a,b,n):

    return b**n - a**n

def Q21_fnc(a,b,n):

    return 0

def Q22_fnc(a,b,n):

    return b**n


Running first of tests. [1 pt]

In [82]:
def Mn_fnc(a,b,n):
    Q11 = Q11_fnc(a,b,n)
    Q12 = Q12_fnc(a,b,n)
    Q21 = Q21_fnc(a,b,n)
    Q22 = Q22_fnc(a,b,n)

    return np.array([[Q11,Q12],[Q21,Q22]])

# Calculating the inverse of an example using the functions
a = 8
b = 6
n = 4
Mn = Mn_fnc(a,b,n)
print('Power of Matrix M computed:')
print(Mn)

# This is the actual matrix
Mn_true = np.array([[4096,-2800],[0,1296]])

# Checking that the values are close enough
assert AlmostEqual(Mn_true,Mn,3)

Power of Matrix M computed:
[[ 4096 -2800]
 [    0  1296]]


Running second of tests. [1 pt]

In [83]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


### Question 3. [2 pts]

When solving for the values of $a$ and $b$ which make the curve $y=f(x)=a+b\cdot 2^x$ go through the $(x,y)$ points $(0,y_1)$ and $(1,y_2)$ for some scalars $y_1$ and $y_2$, we can pose this problem as finding the solution of the following set of equations expressed in matrix form:
$$
\begin{bmatrix} y_1 \\ y_2 \end{bmatrix} =
\begin{bmatrix} m_{11} & m_{12} \\ m_{21} & m_{22} \end{bmatrix} ⋅
\begin{bmatrix} a \\ *b* \end{bmatrix}
$$

Specify what each term $m_{ij}$ is below. **Hint:** Each term is just a constant value, i.e. there are no dependencies on $y_1$ or $y_2$.

In [84]:
# Initializing the values of mij
m11 = m12 = m21 = m22 = 0

m11 = 1
m12 = 1
m21 = 1
m22 = 2

Running set of tests. [2 pts]

In [85]:
# Defining the matrix M
M = np.array([[m11,m12],[m21,m22]])
print('Matrix M Defined:')
print(M)

# Solving for a and b for sample values of y1 and y2
y1 = 2
y2 = 4
ab = np.matmul(np.linalg.inv(M),np.array([y1,y2]))
print('a = {} | b = {}'.format(ab[0],ab[1]))

###
### AUTOGRADER TEST - DO NOT REMOVE
###


Matrix M Defined:
[[1 1]
 [1 2]]
a = 0.0 | b = 2.0



### Question 4. [2 pts]

Let $A$, $B$ and $C$ be $n \times n$ invertible matrices. Provide an expression for $X$ that solves the equation $C^{-1}(A+X)B^{-1}=I_n$, where $I_n$ is the $n \times n$ identity matrix.

Implement this expression in the functions below.

In [86]:
def X_fnc(A,B,C):
  
    return np.dot(C,B)-A

In [87]:
# Calculating X for a particular example
A = np.array([[7,-11],[1,8]])
B = np.array([[6,0],[0,10]])
C = np.array([[17,4],[0,32]])
X = X_fnc(A,B,C)
print('Matrix X Computed:')
print(X)

###
### AUTOGRADER TEST - DO NOT REMOVE
###


Matrix X Computed:
[[ 95  51]
 [ -1 312]]


In [88]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###
